import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HTML from '@/i18n/components/HTML'
import I18nProvider from '@/i18n/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <HTML>
      <I18nProvider />
      <body className={inter.className}>{children}</body>
    </HTML>
  )
}
